#!/bin/bash

usage() {
    echo "Usage: $0 <mysql|sa|sqlalchemy|git|tmux|bash>" >&2
    exit 0
}

case $1 in
    mysql)
        service mysql start

        echo "Initializing mydb..."
        mysql -uroot < scripts/mysql-init
        python /scripts/mysql-default-data

        mysql -uroot --init-command='USE mydb'
        ;;
    sa|sqlalchemy)
        service mysql start

        echo "Initializing mydb..."
        mysql -uroot < scripts/mysql-init

        PYTHONSTARTUP=/scripts/mysql-default-data ipython
        ;;
    git)
        bash scripts/git-init
        echo "alias ohshit='cd ~ && rm -rf ~/git-playground && bash /scripts/git-init && cd ~/git-playground'" >> ~/.aliases
        echo "alias ohhelp='cat ~/README.md'" >> ~/.aliases
        echo "bash /scripts/git-banner" >> ~/.bashrc
        cd ~/git-playground
        tmux
        ;;
    tmux)
        tmux
        bash
        ;;
    bash)
        bash
        ;;
    *)
        usage
        ;;
esac
